image:
- Visual Studio 2017
#- Ubuntu  # unstable CI image

stack: python 3

environment:
  PY_DIR: C:\Python36-x64

clone_depth: 3

before_build:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

build_script:
- pip install -e .[tests]
  
after_build:
- pytest -sv

